services:
  app:
    build: .
    image: exportdashcam:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./clips:/app/clips:ro
    environment:
      NEXT_PUBLIC_ENABLE_UPLOAD_BOX: false
      NEXT_PUBLIC_ENABLE_LIBRARY_REVIEW: true
      NEXT_PUBLIC_ENABLE_SERVER_LIBRARY_CONFIG: false
